sudo: false
dist: bionic
language: node_js
node_js:
- 6
env:
- TSI2_LING7='build'
branches:
  only:
  - master
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
deploy:
  provider: pages
  fqdn: xn--v0qr21b.xn--kpry57d
  skip_cleanup: true
  local_dir: build/
  github_token:
    secure: MnhynOLn/juk7WWVQSo2tUj8IurZh2RtIJSA8yV3BiwUtZp8383n1Op0cfpVWW+G6v3x2IVUR5mA0oHsr686K0ptJQAy3SwnhVrmPB2bakc8C2+c5INC5uibUK6dht7g/xtHA4eWLHud8FtAKwai0AWAxf7NX4y+bRPyRvv6F5xgJq9INinJZ8NJF/Gag31IwR5C+J5AgLi5XJLTTkGa5jVgMV3eXzwFikCx9ewKcvV9nBvUA3jMu/h1N6tOhIN1mx0gt/58qboYfvXPNW5kFOwpuf0vbRjl1ZEiFpFMhzsMLK0Zr0s6OqyCNJXOzaBJF+beZo3ZeTbpPaXJ9mQTgfIM4HEtaqnsl9oC/8X7RarSob60yVSaPA6ewlyrTQLy1mlWaX7oNdaaASTfqFN/c7p0ULDhqcPeYYxS70eYI2l/N2z7/oA6Rna074WM89Sy7haJ/07koMMCzkLSeBCICyAliHO/y4VFsh7Hma0JWJYik9gNeWOJqh4VZO/uYKHBaE18EFxEeCSh4L+ZRitiU5EsCfwrLps7l1NQdVIYqcrU/xx0Ne0GyTOYDKnBs6ollW/KJh4RYympFtrXh3edrAjzgK2p8atbymWtxeJODfkwJWVt15J/cplJDuyigC9Ai1srQsnjTVHx1kE/iiddS7VCr6HAsjFezKP6EmTYaT8=
  on:
    branch: master
    condition: "$TSI2_LING7 = 'build'"
